### ISSUE TITLE
500 Error 

### ISSUE THREAD

**Issue by NorHei** [apeisa/UserGroups#39] opened 2015-01-06 18:47 UTC
ProcessWire 2.5.10 dev
PHP Version 5.5.9-1ubuntu4.5
fastCGI

After installing the hook module i get  500 internal server error 
```
[Tue Dec 30 18:39:56.929767 2014] [core:error] [pid 26496] [client 84.60.116.85:59731] End of script output before headers: index.php
[Tue Dec 30 18:40:00.324062 2014] [fcgid:warn] [pid 26475] (104)Connection reset by peer: [client 84.60.116.85:59733] mod_fcgid: error reading data from FastCGI server
```
I did several experiment whith this and some other servers.
Whith an empty(basic) template this error doe not appear.
I can stop the error by outcommenting the following line in my template 
```
background: url(<?=$pages->get("/settings/template-spot/")->image->url?>) no-repeat center top; 
```
If the module isn't installed it simply gives the image URL
Same problem whith files instead of image.

Tested this on another Server:
PHP Version 5.5.19
FreeBSD 10.0-RELEASE-p12
ProcessWire 2.5.10 dev
fastCGI

500 Server error again this time 
```
<b>Fatal error</b>:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 130968 bytes) in <b>/files/web/www.heimsath.org/incoming/heimsath/wire/core/Wire.php
```
I tested memory usage whithout module and it said 16 mb  so memory usage was suddenly pushed to 130 MB abter module installed .

I experimented a bit by  outcomment the hooks one by one when i outcommented __isPublic__ page was functional again.

I tried some more and found tthat anytime __getAccessPage__  returns anything els but false i run in this memory(500 error) issue.

Thats all i got for you so far .

I can give you acces to the server if you want , and or send you a tarball of my installation to test.

**Comment by teppokoivula** [comment] 2015-01-14 06:18
@NorHei: so far I've been unable to reproduce this. If you could provide us a minimal test case, that would be most helpful; that one line of code you've posted, alone, doesn't seem to result in this bug for me. Any additional details would help too; if there's anything else in Apache or PW error log files, etc.

If log files show nothing else and PW update doesn't help either, it would be a process of elimination; it seems that you've identified UserGroupsHooks::isPublic as the culprit, so I'd start by adding "return" after each specific check in there to see what is actually causing this (or if the cause is as simple as a negative result from this check, i.e. $event->replace = true + $event->return = false).

Also, could you test this with latest ProcessWire version? I've been testing with 2.5.3 and 2.5.14 dev so far without issues. I'm assuming that you're running default (non-modified) .htaccess, and have nothing special in your /site/config.php, index.php etc. files either, by the way.

The PHP versions I've tested are 5.4.34, 5.5.19 and 5.6.2, so not exactly your versions, but hopefully close enough. FastCGI is pretty much new to me, so I'm wondering if it could make a difference here -- you wouldn't happen to have a server where PHP runs without it, would you? :)

**Comment by NorHei** [comment] 2015-01-15 18:12
Googling for the error message  i found several issues concerning only fastcgi and its configurations , a few i could  eleminate in serversettings. tested it right now whith 4 different fcgi webspaces/Server so i think its unlikly that its only a fcgi config thing.   

Guess i do two things: Build a minified testcase and setup an apache whith php as module for testing.
As i am pretty busy right now i guess that will take a few days, but i'l be back and upload the tesstcase here.

**Comment by teppokoivula** [comment] 2015-06-11 14:06
@NorHei While I was going through old issues, this came up. Just checking, but did you ever set up that test case you mentioned earlier? :)

**Comment by NorHei** [comment] 2015-06-18 14:08
I did a few more tests whith that old installation, but it seemed that it came from some strange variable collisions (but thats just a guess).  I upgraded to the latest stable PW version(2.6.1) and all problems where gone, so i  guess we can close this.

**Comment by teppokoivula** [comment] 2015-06-19 16:47
Thanks for the update. I'm closing this issue.

**Closed by teppokoivula** 2015-06-19 16:47 UTC
Labels: discussion
